/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ESI.Client;
using ESI.Model;

namespace ESI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFittingsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete fitting
        /// </summary>
        /// <remarks>
        /// Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns></returns>
        void DeleteCharactersCharacterIdFittingsFittingId (int? characterId, int? fittingId, string datasource = null);

        /// <summary>
        /// Delete fitting
        /// </summary>
        /// <remarks>
        /// Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteCharactersCharacterIdFittingsFittingIdWithHttpInfo (int? characterId, int? fittingId, string datasource = null);
        /// <summary>
        /// Get fittings
        /// </summary>
        /// <remarks>
        /// Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        List<GetCharactersCharacterIdFittings200Ok> GetCharactersCharacterIdFittings (int? characterId, string datasource = null);

        /// <summary>
        /// Get fittings
        /// </summary>
        /// <remarks>
        /// Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        ApiResponse<List<GetCharactersCharacterIdFittings200Ok>> GetCharactersCharacterIdFittingsWithHttpInfo (int? characterId, string datasource = null);
        /// <summary>
        /// Create fitting
        /// </summary>
        /// <remarks>
        /// Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>PostCharactersCharacterIdFittingsCreated</returns>
        PostCharactersCharacterIdFittingsCreated PostCharactersCharacterIdFittings (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null);

        /// <summary>
        /// Create fitting
        /// </summary>
        /// <remarks>
        /// Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of PostCharactersCharacterIdFittingsCreated</returns>
        ApiResponse<PostCharactersCharacterIdFittingsCreated> PostCharactersCharacterIdFittingsWithHttpInfo (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete fitting
        /// </summary>
        /// <remarks>
        /// Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteCharactersCharacterIdFittingsFittingIdAsync (int? characterId, int? fittingId, string datasource = null);

        /// <summary>
        /// Delete fitting
        /// </summary>
        /// <remarks>
        /// Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteCharactersCharacterIdFittingsFittingIdAsyncWithHttpInfo (int? characterId, int? fittingId, string datasource = null);
        /// <summary>
        /// Get fittings
        /// </summary>
        /// <remarks>
        /// Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        System.Threading.Tasks.Task<List<GetCharactersCharacterIdFittings200Ok>> GetCharactersCharacterIdFittingsAsync (int? characterId, string datasource = null);

        /// <summary>
        /// Get fittings
        /// </summary>
        /// <remarks>
        /// Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (List&lt;GetCharactersCharacterIdFittings200Ok&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<GetCharactersCharacterIdFittings200Ok>>> GetCharactersCharacterIdFittingsAsyncWithHttpInfo (int? characterId, string datasource = null);
        /// <summary>
        /// Create fitting
        /// </summary>
        /// <remarks>
        /// Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of PostCharactersCharacterIdFittingsCreated</returns>
        System.Threading.Tasks.Task<PostCharactersCharacterIdFittingsCreated> PostCharactersCharacterIdFittingsAsync (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null);

        /// <summary>
        /// Create fitting
        /// </summary>
        /// <remarks>
        /// Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (PostCharactersCharacterIdFittingsCreated)</returns>
        System.Threading.Tasks.Task<ApiResponse<PostCharactersCharacterIdFittingsCreated>> PostCharactersCharacterIdFittingsAsyncWithHttpInfo (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FittingsApi : IFittingsApi
    {
        private ESI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FittingsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FittingsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = ESI.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FittingsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FittingsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ESI.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ESI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete fitting Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns></returns>
        public void DeleteCharactersCharacterIdFittingsFittingId (int? characterId, int? fittingId, string datasource = null)
        {
             DeleteCharactersCharacterIdFittingsFittingIdWithHttpInfo(characterId, fittingId, datasource);
        }

        /// <summary>
        /// Delete fitting Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteCharactersCharacterIdFittingsFittingIdWithHttpInfo (int? characterId, int? fittingId, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->DeleteCharactersCharacterIdFittingsFittingId");
            // verify the required parameter 'fittingId' is set
            if (fittingId == null)
                throw new ApiException(400, "Missing required parameter 'fittingId' when calling FittingsApi->DeleteCharactersCharacterIdFittingsFittingId");

            var localVarPath = "/characters/{character_id}/fittings/{fitting_id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (fittingId != null) localVarPathParams.Add("fitting_id", Configuration.ApiClient.ParameterToString(fittingId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCharactersCharacterIdFittingsFittingId", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete fitting Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteCharactersCharacterIdFittingsFittingIdAsync (int? characterId, int? fittingId, string datasource = null)
        {
             await DeleteCharactersCharacterIdFittingsFittingIdAsyncWithHttpInfo(characterId, fittingId, datasource);

        }

        /// <summary>
        /// Delete fitting Delete a fitting from a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/{fitting_id}/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/{fitting_id}/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fittingId">ID for a fitting of this character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteCharactersCharacterIdFittingsFittingIdAsyncWithHttpInfo (int? characterId, int? fittingId, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->DeleteCharactersCharacterIdFittingsFittingId");
            // verify the required parameter 'fittingId' is set
            if (fittingId == null)
                throw new ApiException(400, "Missing required parameter 'fittingId' when calling FittingsApi->DeleteCharactersCharacterIdFittingsFittingId");

            var localVarPath = "/characters/{character_id}/fittings/{fitting_id}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (fittingId != null) localVarPathParams.Add("fitting_id", Configuration.ApiClient.ParameterToString(fittingId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCharactersCharacterIdFittingsFittingId", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get fittings Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        public List<GetCharactersCharacterIdFittings200Ok> GetCharactersCharacterIdFittings (int? characterId, string datasource = null)
        {
             ApiResponse<List<GetCharactersCharacterIdFittings200Ok>> localVarResponse = GetCharactersCharacterIdFittingsWithHttpInfo(characterId, datasource);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get fittings Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        public ApiResponse< List<GetCharactersCharacterIdFittings200Ok> > GetCharactersCharacterIdFittingsWithHttpInfo (int? characterId, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->GetCharactersCharacterIdFittings");

            var localVarPath = "/characters/{character_id}/fittings/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCharactersCharacterIdFittings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<GetCharactersCharacterIdFittings200Ok>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<GetCharactersCharacterIdFittings200Ok>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<GetCharactersCharacterIdFittings200Ok>)));
            
        }

        /// <summary>
        /// Get fittings Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of List&lt;GetCharactersCharacterIdFittings200Ok&gt;</returns>
        public async System.Threading.Tasks.Task<List<GetCharactersCharacterIdFittings200Ok>> GetCharactersCharacterIdFittingsAsync (int? characterId, string datasource = null)
        {
             ApiResponse<List<GetCharactersCharacterIdFittings200Ok>> localVarResponse = await GetCharactersCharacterIdFittingsAsyncWithHttpInfo(characterId, datasource);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get fittings Return fittings of a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60;   - --  This route is cached for up to 300 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (List&lt;GetCharactersCharacterIdFittings200Ok&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<GetCharactersCharacterIdFittings200Ok>>> GetCharactersCharacterIdFittingsAsyncWithHttpInfo (int? characterId, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->GetCharactersCharacterIdFittings");

            var localVarPath = "/characters/{character_id}/fittings/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCharactersCharacterIdFittings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<GetCharactersCharacterIdFittings200Ok>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<GetCharactersCharacterIdFittings200Ok>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<GetCharactersCharacterIdFittings200Ok>)));
            
        }

        /// <summary>
        /// Create fitting Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>PostCharactersCharacterIdFittingsCreated</returns>
        public PostCharactersCharacterIdFittingsCreated PostCharactersCharacterIdFittings (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null)
        {
             ApiResponse<PostCharactersCharacterIdFittingsCreated> localVarResponse = PostCharactersCharacterIdFittingsWithHttpInfo(characterId, fitting, datasource);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create fitting Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of PostCharactersCharacterIdFittingsCreated</returns>
        public ApiResponse< PostCharactersCharacterIdFittingsCreated > PostCharactersCharacterIdFittingsWithHttpInfo (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->PostCharactersCharacterIdFittings");

            var localVarPath = "/characters/{character_id}/fittings/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter
            if (fitting != null && fitting.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(fitting); // http body (model) parameter
            }
            else
            {
                localVarPostBody = fitting; // byte array
            }

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostCharactersCharacterIdFittings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PostCharactersCharacterIdFittingsCreated>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PostCharactersCharacterIdFittingsCreated) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PostCharactersCharacterIdFittingsCreated)));
            
        }

        /// <summary>
        /// Create fitting Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of PostCharactersCharacterIdFittingsCreated</returns>
        public async System.Threading.Tasks.Task<PostCharactersCharacterIdFittingsCreated> PostCharactersCharacterIdFittingsAsync (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null)
        {
             ApiResponse<PostCharactersCharacterIdFittingsCreated> localVarResponse = await PostCharactersCharacterIdFittingsAsyncWithHttpInfo(characterId, fitting, datasource);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create fitting Save a new fitting for a character  - --  Alternate route: &#x60;/v1/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fittings/&#x60;  Alternate route: &#x60;/latest/characters/{character_id}/fittings/&#x60; 
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">ID for a character</param>
        /// <param name="fitting">Details about the new fitting (optional)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (PostCharactersCharacterIdFittingsCreated)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PostCharactersCharacterIdFittingsCreated>> PostCharactersCharacterIdFittingsAsyncWithHttpInfo (int? characterId, PostCharactersCharacterIdFittingsFitting fitting = null, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling FittingsApi->PostCharactersCharacterIdFittings");

            var localVarPath = "/characters/{character_id}/fittings/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter
            if (fitting != null && fitting.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(fitting); // http body (model) parameter
            }
            else
            {
                localVarPostBody = fitting; // byte array
            }

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostCharactersCharacterIdFittings", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PostCharactersCharacterIdFittingsCreated>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PostCharactersCharacterIdFittingsCreated) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PostCharactersCharacterIdFittingsCreated)));
            
        }

    }
}
