/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ESI.Client;
using ESI.Model;

namespace ESI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>GetCharactersCharacterIdSearchOk</returns>
        GetCharactersCharacterIdSearchOk GetCharactersCharacterIdSearch (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);

        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of GetCharactersCharacterIdSearchOk</returns>
        ApiResponse<GetCharactersCharacterIdSearchOk> GetCharactersCharacterIdSearchWithHttpInfo (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);
        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>GetSearchOk</returns>
        GetSearchOk GetSearch (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);

        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of GetSearchOk</returns>
        ApiResponse<GetSearchOk> GetSearchWithHttpInfo (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of GetCharactersCharacterIdSearchOk</returns>
        System.Threading.Tasks.Task<GetCharactersCharacterIdSearchOk> GetCharactersCharacterIdSearchAsync (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);

        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (GetCharactersCharacterIdSearchOk)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetCharactersCharacterIdSearchOk>> GetCharactersCharacterIdSearchAsyncWithHttpInfo (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);
        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of GetSearchOk</returns>
        System.Threading.Tasks.Task<GetSearchOk> GetSearchAsync (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);

        /// <summary>
        /// Search on a string
        /// </summary>
        /// <remarks>
        /// Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </remarks>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (GetSearchOk)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetSearchOk>> GetSearchAsyncWithHttpInfo (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SearchApi : ISearchApi
    {
        private ESI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SearchApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = ESI.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SearchApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ESI.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ESI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>GetCharactersCharacterIdSearchOk</returns>
        public GetCharactersCharacterIdSearchOk GetCharactersCharacterIdSearch (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
             ApiResponse<GetCharactersCharacterIdSearchOk> localVarResponse = GetCharactersCharacterIdSearchWithHttpInfo(characterId, search, categories, language, strict, datasource);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of GetCharactersCharacterIdSearchOk</returns>
        public ApiResponse< GetCharactersCharacterIdSearchOk > GetCharactersCharacterIdSearchWithHttpInfo (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling SearchApi->GetCharactersCharacterIdSearch");
            // verify the required parameter 'search' is set
            if (search == null)
                throw new ApiException(400, "Missing required parameter 'search' when calling SearchApi->GetCharactersCharacterIdSearch");
            // verify the required parameter 'categories' is set
            if (categories == null)
                throw new ApiException(400, "Missing required parameter 'categories' when calling SearchApi->GetCharactersCharacterIdSearch");

            var localVarPath = "/characters/{character_id}/search/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (search != null) localVarQueryParams.Add("search", Configuration.ApiClient.ParameterToString(search)); // query parameter
            if (categories != null) localVarQueryParams.Add("categories", Configuration.ApiClient.ParameterToString(categories)); // query parameter
            if (language != null) localVarQueryParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // query parameter
            if (strict != null) localVarQueryParams.Add("strict", Configuration.ApiClient.ParameterToString(strict)); // query parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCharactersCharacterIdSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCharactersCharacterIdSearchOk>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetCharactersCharacterIdSearchOk) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCharactersCharacterIdSearchOk)));
            
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of GetCharactersCharacterIdSearchOk</returns>
        public async System.Threading.Tasks.Task<GetCharactersCharacterIdSearchOk> GetCharactersCharacterIdSearchAsync (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
             ApiResponse<GetCharactersCharacterIdSearchOk> localVarResponse = await GetCharactersCharacterIdSearchAsyncWithHttpInfo(characterId, search, categories, language, strict, datasource);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v3/characters/{character_id}/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characterId">An EVE character ID</param>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (GetCharactersCharacterIdSearchOk)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetCharactersCharacterIdSearchOk>> GetCharactersCharacterIdSearchAsyncWithHttpInfo (int? characterId, string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
            // verify the required parameter 'characterId' is set
            if (characterId == null)
                throw new ApiException(400, "Missing required parameter 'characterId' when calling SearchApi->GetCharactersCharacterIdSearch");
            // verify the required parameter 'search' is set
            if (search == null)
                throw new ApiException(400, "Missing required parameter 'search' when calling SearchApi->GetCharactersCharacterIdSearch");
            // verify the required parameter 'categories' is set
            if (categories == null)
                throw new ApiException(400, "Missing required parameter 'categories' when calling SearchApi->GetCharactersCharacterIdSearch");

            var localVarPath = "/characters/{character_id}/search/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (characterId != null) localVarPathParams.Add("character_id", Configuration.ApiClient.ParameterToString(characterId)); // path parameter
            if (search != null) localVarQueryParams.Add("search", Configuration.ApiClient.ParameterToString(search)); // query parameter
            if (categories != null) localVarQueryParams.Add("categories", Configuration.ApiClient.ParameterToString(categories)); // query parameter
            if (language != null) localVarQueryParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // query parameter
            if (strict != null) localVarQueryParams.Add("strict", Configuration.ApiClient.ParameterToString(strict)); // query parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter

            // authentication (evesso) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCharactersCharacterIdSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCharactersCharacterIdSearchOk>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetCharactersCharacterIdSearchOk) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCharactersCharacterIdSearchOk)));
            
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>GetSearchOk</returns>
        public GetSearchOk GetSearch (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
             ApiResponse<GetSearchOk> localVarResponse = GetSearchWithHttpInfo(search, categories, language, strict, datasource);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>ApiResponse of GetSearchOk</returns>
        public ApiResponse< GetSearchOk > GetSearchWithHttpInfo (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
            // verify the required parameter 'search' is set
            if (search == null)
                throw new ApiException(400, "Missing required parameter 'search' when calling SearchApi->GetSearch");
            // verify the required parameter 'categories' is set
            if (categories == null)
                throw new ApiException(400, "Missing required parameter 'categories' when calling SearchApi->GetSearch");

            var localVarPath = "/search/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (search != null) localVarQueryParams.Add("search", Configuration.ApiClient.ParameterToString(search)); // query parameter
            if (categories != null) localVarQueryParams.Add("categories", Configuration.ApiClient.ParameterToString(categories)); // query parameter
            if (language != null) localVarQueryParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // query parameter
            if (strict != null) localVarQueryParams.Add("strict", Configuration.ApiClient.ParameterToString(strict)); // query parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetSearchOk>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetSearchOk) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetSearchOk)));
            
        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of GetSearchOk</returns>
        public async System.Threading.Tasks.Task<GetSearchOk> GetSearchAsync (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
             ApiResponse<GetSearchOk> localVarResponse = await GetSearchAsyncWithHttpInfo(search, categories, language, strict, datasource);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search on a string Search for entities that match a given sub-string.  - --  Alternate route: &#x60;/v2/search/&#x60;   - --  This route is cached for up to 3600 seconds
        /// </summary>
        /// <exception cref="ESI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="search">The string to search on</param>
        /// <param name="categories">Type of entities to search for</param>
        /// <param name="language">Search locale (optional, default to en-us)</param>
        /// <param name="strict">Whether the search should be a strict match (optional, default to false)</param>
        /// <param name="datasource">The server name you would like data from (optional, default to tranquility)</param>
        /// <returns>Task of ApiResponse (GetSearchOk)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetSearchOk>> GetSearchAsyncWithHttpInfo (string search, List<string> categories, string language = null, bool? strict = null, string datasource = null)
        {
            // verify the required parameter 'search' is set
            if (search == null)
                throw new ApiException(400, "Missing required parameter 'search' when calling SearchApi->GetSearch");
            // verify the required parameter 'categories' is set
            if (categories == null)
                throw new ApiException(400, "Missing required parameter 'categories' when calling SearchApi->GetSearch");

            var localVarPath = "/search/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (search != null) localVarQueryParams.Add("search", Configuration.ApiClient.ParameterToString(search)); // query parameter
            if (categories != null) localVarQueryParams.Add("categories", Configuration.ApiClient.ParameterToString(categories)); // query parameter
            if (language != null) localVarQueryParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // query parameter
            if (strict != null) localVarQueryParams.Add("strict", Configuration.ApiClient.ParameterToString(strict)); // query parameter
            if (datasource != null) localVarQueryParams.Add("datasource", Configuration.ApiClient.ParameterToString(datasource)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSearch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetSearchOk>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetSearchOk) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetSearchOk)));
            
        }

    }
}
