/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetAlliancesNames200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAlliancesNames200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetAlliancesNames200Ok
        //private GetAlliancesNames200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAlliancesNames200Ok
            //instance = new GetAlliancesNames200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAlliancesNames200Ok
        /// </summary>
        [Test]
        public void GetAlliancesNames200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAlliancesNames200Ok
            //Assert.IsInstanceOfType<GetAlliancesNames200Ok> (instance, "variable 'instance' is a GetAlliancesNames200Ok");
        }

        /// <summary>
        /// Test the property 'AllianceId'
        /// </summary>
        [Test]
        public void AllianceIdTest()
        {
            // TODO unit test for the property 'AllianceId'
        }
        /// <summary>
        /// Test the property 'AllianceName'
        /// </summary>
        [Test]
        public void AllianceNameTest()
        {
            // TODO unit test for the property 'AllianceName'
        }

    }

}
