/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetAlliancesAllianceIdIconsOk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAlliancesAllianceIdIconsOkTests
    {
        // TODO uncomment below to declare an instance variable for GetAlliancesAllianceIdIconsOk
        //private GetAlliancesAllianceIdIconsOk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAlliancesAllianceIdIconsOk
            //instance = new GetAlliancesAllianceIdIconsOk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAlliancesAllianceIdIconsOk
        /// </summary>
        [Test]
        public void GetAlliancesAllianceIdIconsOkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAlliancesAllianceIdIconsOk
            //Assert.IsInstanceOfType<GetAlliancesAllianceIdIconsOk> (instance, "variable 'instance' is a GetAlliancesAllianceIdIconsOk");
        }

        /// <summary>
        /// Test the property 'Px128x128'
        /// </summary>
        [Test]
        public void Px128x128Test()
        {
            // TODO unit test for the property 'Px128x128'
        }
        /// <summary>
        /// Test the property 'Px64x64'
        /// </summary>
        [Test]
        public void Px64x64Test()
        {
            // TODO unit test for the property 'Px64x64'
        }

    }

}
