/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCharactersCharacterIdPlanets200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCharactersCharacterIdPlanets200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetCharactersCharacterIdPlanets200Ok
        //private GetCharactersCharacterIdPlanets200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCharactersCharacterIdPlanets200Ok
            //instance = new GetCharactersCharacterIdPlanets200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCharactersCharacterIdPlanets200Ok
        /// </summary>
        [Test]
        public void GetCharactersCharacterIdPlanets200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCharactersCharacterIdPlanets200Ok
            //Assert.IsInstanceOfType<GetCharactersCharacterIdPlanets200Ok> (instance, "variable 'instance' is a GetCharactersCharacterIdPlanets200Ok");
        }

        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Test]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'NumPins'
        /// </summary>
        [Test]
        public void NumPinsTest()
        {
            // TODO unit test for the property 'NumPins'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'PlanetId'
        /// </summary>
        [Test]
        public void PlanetIdTest()
        {
            // TODO unit test for the property 'PlanetId'
        }
        /// <summary>
        /// Test the property 'PlanetType'
        /// </summary>
        [Test]
        public void PlanetTypeTest()
        {
            // TODO unit test for the property 'PlanetType'
        }
        /// <summary>
        /// Test the property 'SolarSystemId'
        /// </summary>
        [Test]
        public void SolarSystemIdTest()
        {
            // TODO unit test for the property 'SolarSystemId'
        }
        /// <summary>
        /// Test the property 'UpgradeLevel'
        /// </summary>
        [Test]
        public void UpgradeLevelTest()
        {
            // TODO unit test for the property 'UpgradeLevel'
        }

    }

}
