/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCharactersCharacterIdCalendar200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCharactersCharacterIdCalendar200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetCharactersCharacterIdCalendar200Ok
        //private GetCharactersCharacterIdCalendar200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCharactersCharacterIdCalendar200Ok
            //instance = new GetCharactersCharacterIdCalendar200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCharactersCharacterIdCalendar200Ok
        /// </summary>
        [Test]
        public void GetCharactersCharacterIdCalendar200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCharactersCharacterIdCalendar200Ok
            //Assert.IsInstanceOfType<GetCharactersCharacterIdCalendar200Ok> (instance, "variable 'instance' is a GetCharactersCharacterIdCalendar200Ok");
        }

        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Test]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Test]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'EventResponse'
        /// </summary>
        [Test]
        public void EventResponseTest()
        {
            // TODO unit test for the property 'EventResponse'
        }
        /// <summary>
        /// Test the property 'Importance'
        /// </summary>
        [Test]
        public void ImportanceTest()
        {
            // TODO unit test for the property 'Importance'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
