/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCorporationsNames200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCorporationsNames200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetCorporationsNames200Ok
        //private GetCorporationsNames200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCorporationsNames200Ok
            //instance = new GetCorporationsNames200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCorporationsNames200Ok
        /// </summary>
        [Test]
        public void GetCorporationsNames200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCorporationsNames200Ok
            //Assert.IsInstanceOfType<GetCorporationsNames200Ok> (instance, "variable 'instance' is a GetCorporationsNames200Ok");
        }

        /// <summary>
        /// Test the property 'CorporationId'
        /// </summary>
        [Test]
        public void CorporationIdTest()
        {
            // TODO unit test for the property 'CorporationId'
        }
        /// <summary>
        /// Test the property 'CorporationName'
        /// </summary>
        [Test]
        public void CorporationNameTest()
        {
            // TODO unit test for the property 'CorporationName'
        }

    }

}
