/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCharactersCharacterIdSkillsSkill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCharactersCharacterIdSkillsSkillTests
    {
        // TODO uncomment below to declare an instance variable for GetCharactersCharacterIdSkillsSkill
        //private GetCharactersCharacterIdSkillsSkill instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCharactersCharacterIdSkillsSkill
            //instance = new GetCharactersCharacterIdSkillsSkill();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCharactersCharacterIdSkillsSkill
        /// </summary>
        [Test]
        public void GetCharactersCharacterIdSkillsSkillInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCharactersCharacterIdSkillsSkill
            //Assert.IsInstanceOfType<GetCharactersCharacterIdSkillsSkill> (instance, "variable 'instance' is a GetCharactersCharacterIdSkillsSkill");
        }

        /// <summary>
        /// Test the property 'CurrentSkillLevel'
        /// </summary>
        [Test]
        public void CurrentSkillLevelTest()
        {
            // TODO unit test for the property 'CurrentSkillLevel'
        }
        /// <summary>
        /// Test the property 'SkillId'
        /// </summary>
        [Test]
        public void SkillIdTest()
        {
            // TODO unit test for the property 'SkillId'
        }
        /// <summary>
        /// Test the property 'SkillpointsInSkill'
        /// </summary>
        [Test]
        public void SkillpointsInSkillTest()
        {
            // TODO unit test for the property 'SkillpointsInSkill'
        }

    }

}
