/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCharactersCharacterIdMailLabelsLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCharactersCharacterIdMailLabelsLabelTests
    {
        // TODO uncomment below to declare an instance variable for GetCharactersCharacterIdMailLabelsLabel
        //private GetCharactersCharacterIdMailLabelsLabel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCharactersCharacterIdMailLabelsLabel
            //instance = new GetCharactersCharacterIdMailLabelsLabel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCharactersCharacterIdMailLabelsLabel
        /// </summary>
        [Test]
        public void GetCharactersCharacterIdMailLabelsLabelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCharactersCharacterIdMailLabelsLabel
            //Assert.IsInstanceOfType<GetCharactersCharacterIdMailLabelsLabel> (instance, "variable 'instance' is a GetCharactersCharacterIdMailLabelsLabel");
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'LabelId'
        /// </summary>
        [Test]
        public void LabelIdTest()
        {
            // TODO unit test for the property 'LabelId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UnreadCount'
        /// </summary>
        [Test]
        public void UnreadCountTest()
        {
            // TODO unit test for the property 'UnreadCount'
        }

    }

}
