/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetCharactersCharacterIdCorporationhistory200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCharactersCharacterIdCorporationhistory200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetCharactersCharacterIdCorporationhistory200Ok
        //private GetCharactersCharacterIdCorporationhistory200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCharactersCharacterIdCorporationhistory200Ok
            //instance = new GetCharactersCharacterIdCorporationhistory200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCharactersCharacterIdCorporationhistory200Ok
        /// </summary>
        [Test]
        public void GetCharactersCharacterIdCorporationhistory200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCharactersCharacterIdCorporationhistory200Ok
            //Assert.IsInstanceOfType<GetCharactersCharacterIdCorporationhistory200Ok> (instance, "variable 'instance' is a GetCharactersCharacterIdCorporationhistory200Ok");
        }

        /// <summary>
        /// Test the property 'CorporationId'
        /// </summary>
        [Test]
        public void CorporationIdTest()
        {
            // TODO unit test for the property 'CorporationId'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Test]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
        /// <summary>
        /// Test the property 'RecordId'
        /// </summary>
        [Test]
        public void RecordIdTest()
        {
            // TODO unit test for the property 'RecordId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

    }

}
