/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetKillmailsKillmailIdKillmailHashItem1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetKillmailsKillmailIdKillmailHashItem1Tests
    {
        // TODO uncomment below to declare an instance variable for GetKillmailsKillmailIdKillmailHashItem1
        //private GetKillmailsKillmailIdKillmailHashItem1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetKillmailsKillmailIdKillmailHashItem1
            //instance = new GetKillmailsKillmailIdKillmailHashItem1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetKillmailsKillmailIdKillmailHashItem1
        /// </summary>
        [Test]
        public void GetKillmailsKillmailIdKillmailHashItem1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetKillmailsKillmailIdKillmailHashItem1
            //Assert.IsInstanceOfType<GetKillmailsKillmailIdKillmailHashItem1> (instance, "variable 'instance' is a GetKillmailsKillmailIdKillmailHashItem1");
        }

        /// <summary>
        /// Test the property 'Flag'
        /// </summary>
        [Test]
        public void FlagTest()
        {
            // TODO unit test for the property 'Flag'
        }
        /// <summary>
        /// Test the property 'ItemTypeId'
        /// </summary>
        [Test]
        public void ItemTypeIdTest()
        {
            // TODO unit test for the property 'ItemTypeId'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'QuantityDestroyed'
        /// </summary>
        [Test]
        public void QuantityDestroyedTest()
        {
            // TODO unit test for the property 'QuantityDestroyed'
        }
        /// <summary>
        /// Test the property 'QuantityDropped'
        /// </summary>
        [Test]
        public void QuantityDroppedTest()
        {
            // TODO unit test for the property 'QuantityDropped'
        }
        /// <summary>
        /// Test the property 'Singleton'
        /// </summary>
        [Test]
        public void SingletonTest()
        {
            // TODO unit test for the property 'Singleton'
        }

    }

}
