/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetKillmailsKillmailIdKillmailHashOk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetKillmailsKillmailIdKillmailHashOkTests
    {
        // TODO uncomment below to declare an instance variable for GetKillmailsKillmailIdKillmailHashOk
        //private GetKillmailsKillmailIdKillmailHashOk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetKillmailsKillmailIdKillmailHashOk
            //instance = new GetKillmailsKillmailIdKillmailHashOk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetKillmailsKillmailIdKillmailHashOk
        /// </summary>
        [Test]
        public void GetKillmailsKillmailIdKillmailHashOkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetKillmailsKillmailIdKillmailHashOk
            //Assert.IsInstanceOfType<GetKillmailsKillmailIdKillmailHashOk> (instance, "variable 'instance' is a GetKillmailsKillmailIdKillmailHashOk");
        }

        /// <summary>
        /// Test the property 'Attackers'
        /// </summary>
        [Test]
        public void AttackersTest()
        {
            // TODO unit test for the property 'Attackers'
        }
        /// <summary>
        /// Test the property 'KillmailId'
        /// </summary>
        [Test]
        public void KillmailIdTest()
        {
            // TODO unit test for the property 'KillmailId'
        }
        /// <summary>
        /// Test the property 'KillmailTime'
        /// </summary>
        [Test]
        public void KillmailTimeTest()
        {
            // TODO unit test for the property 'KillmailTime'
        }
        /// <summary>
        /// Test the property 'MoonId'
        /// </summary>
        [Test]
        public void MoonIdTest()
        {
            // TODO unit test for the property 'MoonId'
        }
        /// <summary>
        /// Test the property 'SolarSystemId'
        /// </summary>
        [Test]
        public void SolarSystemIdTest()
        {
            // TODO unit test for the property 'SolarSystemId'
        }
        /// <summary>
        /// Test the property 'Victim'
        /// </summary>
        [Test]
        public void VictimTest()
        {
            // TODO unit test for the property 'Victim'
        }
        /// <summary>
        /// Test the property 'WarId'
        /// </summary>
        [Test]
        public void WarIdTest()
        {
            // TODO unit test for the property 'WarId'
        }

    }

}
