/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetMarketsStructuresStructureIdInternalServerError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetMarketsStructuresStructureIdInternalServerErrorTests
    {
        // TODO uncomment below to declare an instance variable for GetMarketsStructuresStructureIdInternalServerError
        //private GetMarketsStructuresStructureIdInternalServerError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetMarketsStructuresStructureIdInternalServerError
            //instance = new GetMarketsStructuresStructureIdInternalServerError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetMarketsStructuresStructureIdInternalServerError
        /// </summary>
        [Test]
        public void GetMarketsStructuresStructureIdInternalServerErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetMarketsStructuresStructureIdInternalServerError
            //Assert.IsInstanceOfType<GetMarketsStructuresStructureIdInternalServerError> (instance, "variable 'instance' is a GetMarketsStructuresStructureIdInternalServerError");
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
