/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetSovereigntyStructures200Ok
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetSovereigntyStructures200OkTests
    {
        // TODO uncomment below to declare an instance variable for GetSovereigntyStructures200Ok
        //private GetSovereigntyStructures200Ok instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSovereigntyStructures200Ok
            //instance = new GetSovereigntyStructures200Ok();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSovereigntyStructures200Ok
        /// </summary>
        [Test]
        public void GetSovereigntyStructures200OkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetSovereigntyStructures200Ok
            //Assert.IsInstanceOfType<GetSovereigntyStructures200Ok> (instance, "variable 'instance' is a GetSovereigntyStructures200Ok");
        }

        /// <summary>
        /// Test the property 'AllianceId'
        /// </summary>
        [Test]
        public void AllianceIdTest()
        {
            // TODO unit test for the property 'AllianceId'
        }
        /// <summary>
        /// Test the property 'SolarSystemId'
        /// </summary>
        [Test]
        public void SolarSystemIdTest()
        {
            // TODO unit test for the property 'SolarSystemId'
        }
        /// <summary>
        /// Test the property 'StructureId'
        /// </summary>
        [Test]
        public void StructureIdTest()
        {
            // TODO unit test for the property 'StructureId'
        }
        /// <summary>
        /// Test the property 'StructureTypeId'
        /// </summary>
        [Test]
        public void StructureTypeIdTest()
        {
            // TODO unit test for the property 'StructureTypeId'
        }
        /// <summary>
        /// Test the property 'VulnerabilityOccupancyLevel'
        /// </summary>
        [Test]
        public void VulnerabilityOccupancyLevelTest()
        {
            // TODO unit test for the property 'VulnerabilityOccupancyLevel'
        }
        /// <summary>
        /// Test the property 'VulnerableEndTime'
        /// </summary>
        [Test]
        public void VulnerableEndTimeTest()
        {
            // TODO unit test for the property 'VulnerableEndTime'
        }
        /// <summary>
        /// Test the property 'VulnerableStartTime'
        /// </summary>
        [Test]
        public void VulnerableStartTimeTest()
        {
            // TODO unit test for the property 'VulnerableStartTime'
        }

    }

}
