/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetUniverseSchematicsSchematicIdOk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetUniverseSchematicsSchematicIdOkTests
    {
        // TODO uncomment below to declare an instance variable for GetUniverseSchematicsSchematicIdOk
        //private GetUniverseSchematicsSchematicIdOk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetUniverseSchematicsSchematicIdOk
            //instance = new GetUniverseSchematicsSchematicIdOk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetUniverseSchematicsSchematicIdOk
        /// </summary>
        [Test]
        public void GetUniverseSchematicsSchematicIdOkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetUniverseSchematicsSchematicIdOk
            //Assert.IsInstanceOfType<GetUniverseSchematicsSchematicIdOk> (instance, "variable 'instance' is a GetUniverseSchematicsSchematicIdOk");
        }

        /// <summary>
        /// Test the property 'CycleTime'
        /// </summary>
        [Test]
        public void CycleTimeTest()
        {
            // TODO unit test for the property 'CycleTime'
        }
        /// <summary>
        /// Test the property 'SchematicName'
        /// </summary>
        [Test]
        public void SchematicNameTest()
        {
            // TODO unit test for the property 'SchematicName'
        }

    }

}
