/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ESI.Api;
using ESI.Model;
using ESI.Client;
using System.Reflection;

namespace ESI.Test
{
    /// <summary>
    ///  Class for testing GetUniverseCategoriesCategoryIdOk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetUniverseCategoriesCategoryIdOkTests
    {
        // TODO uncomment below to declare an instance variable for GetUniverseCategoriesCategoryIdOk
        //private GetUniverseCategoriesCategoryIdOk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetUniverseCategoriesCategoryIdOk
            //instance = new GetUniverseCategoriesCategoryIdOk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetUniverseCategoriesCategoryIdOk
        /// </summary>
        [Test]
        public void GetUniverseCategoriesCategoryIdOkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetUniverseCategoriesCategoryIdOk
            //Assert.IsInstanceOfType<GetUniverseCategoriesCategoryIdOk> (instance, "variable 'instance' is a GetUniverseCategoriesCategoryIdOk");
        }

        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Published'
        /// </summary>
        [Test]
        public void PublishedTest()
        {
            // TODO unit test for the property 'Published'
        }

    }

}
