/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCorporationsCorporationIdOk :  IEquatable<GetCorporationsCorporationIdOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdOk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCorporationsCorporationIdOk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCorporationsCorporationIdOk" /> class.
        /// </summary>
        /// <param name="AllianceId">id of alliance that corporation is a member of, if any.</param>
        /// <param name="CeoId">ceo_id integer (required).</param>
        /// <param name="CorporationDescription">corporation_description string (required).</param>
        /// <param name="CorporationName">the full name of the corporation (required).</param>
        /// <param name="CreationDate">creation_date string (required).</param>
        /// <param name="CreatorId">creator_id integer (required).</param>
        /// <param name="MemberCount">member_count integer (required).</param>
        /// <param name="TaxRate">tax_rate number (required).</param>
        /// <param name="Ticker">the short name of the corporation (required).</param>
        /// <param name="Url">url string (required).</param>
        public GetCorporationsCorporationIdOk(int? AllianceId = default(int?), int? CeoId = default(int?), string CorporationDescription = default(string), string CorporationName = default(string), DateTime? CreationDate = default(DateTime?), int? CreatorId = default(int?), int? MemberCount = default(int?), float? TaxRate = default(float?), string Ticker = default(string), string Url = default(string))
        {
            // to ensure "CeoId" is required (not null)
            if (CeoId == null)
            {
                throw new InvalidDataException("CeoId is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.CeoId = CeoId;
            }
            // to ensure "CorporationDescription" is required (not null)
            if (CorporationDescription == null)
            {
                throw new InvalidDataException("CorporationDescription is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.CorporationDescription = CorporationDescription;
            }
            // to ensure "CorporationName" is required (not null)
            if (CorporationName == null)
            {
                throw new InvalidDataException("CorporationName is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.CorporationName = CorporationName;
            }
            // to ensure "CreationDate" is required (not null)
            if (CreationDate == null)
            {
                throw new InvalidDataException("CreationDate is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.CreationDate = CreationDate;
            }
            // to ensure "CreatorId" is required (not null)
            if (CreatorId == null)
            {
                throw new InvalidDataException("CreatorId is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.CreatorId = CreatorId;
            }
            // to ensure "MemberCount" is required (not null)
            if (MemberCount == null)
            {
                throw new InvalidDataException("MemberCount is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.MemberCount = MemberCount;
            }
            // to ensure "TaxRate" is required (not null)
            if (TaxRate == null)
            {
                throw new InvalidDataException("TaxRate is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.TaxRate = TaxRate;
            }
            // to ensure "Ticker" is required (not null)
            if (Ticker == null)
            {
                throw new InvalidDataException("Ticker is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.Ticker = Ticker;
            }
            // to ensure "Url" is required (not null)
            if (Url == null)
            {
                throw new InvalidDataException("Url is a required property for GetCorporationsCorporationIdOk and cannot be null");
            }
            else
            {
                this.Url = Url;
            }
            this.AllianceId = AllianceId;
        }
        
        /// <summary>
        /// id of alliance that corporation is a member of, if any
        /// </summary>
        /// <value>id of alliance that corporation is a member of, if any</value>
        [DataMember(Name="alliance_id", EmitDefaultValue=false)]
        public int? AllianceId { get; set; }
        /// <summary>
        /// ceo_id integer
        /// </summary>
        /// <value>ceo_id integer</value>
        [DataMember(Name="ceo_id", EmitDefaultValue=false)]
        public int? CeoId { get; set; }
        /// <summary>
        /// corporation_description string
        /// </summary>
        /// <value>corporation_description string</value>
        [DataMember(Name="corporation_description", EmitDefaultValue=false)]
        public string CorporationDescription { get; set; }
        /// <summary>
        /// the full name of the corporation
        /// </summary>
        /// <value>the full name of the corporation</value>
        [DataMember(Name="corporation_name", EmitDefaultValue=false)]
        public string CorporationName { get; set; }
        /// <summary>
        /// creation_date string
        /// </summary>
        /// <value>creation_date string</value>
        [DataMember(Name="creation_date", EmitDefaultValue=false)]
        public DateTime? CreationDate { get; set; }
        /// <summary>
        /// creator_id integer
        /// </summary>
        /// <value>creator_id integer</value>
        [DataMember(Name="creator_id", EmitDefaultValue=false)]
        public int? CreatorId { get; set; }
        /// <summary>
        /// member_count integer
        /// </summary>
        /// <value>member_count integer</value>
        [DataMember(Name="member_count", EmitDefaultValue=false)]
        public int? MemberCount { get; set; }
        /// <summary>
        /// tax_rate number
        /// </summary>
        /// <value>tax_rate number</value>
        [DataMember(Name="tax_rate", EmitDefaultValue=false)]
        public float? TaxRate { get; set; }
        /// <summary>
        /// the short name of the corporation
        /// </summary>
        /// <value>the short name of the corporation</value>
        [DataMember(Name="ticker", EmitDefaultValue=false)]
        public string Ticker { get; set; }
        /// <summary>
        /// url string
        /// </summary>
        /// <value>url string</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCorporationsCorporationIdOk {\n");
            sb.Append("  AllianceId: ").Append(AllianceId).Append("\n");
            sb.Append("  CeoId: ").Append(CeoId).Append("\n");
            sb.Append("  CorporationDescription: ").Append(CorporationDescription).Append("\n");
            sb.Append("  CorporationName: ").Append(CorporationName).Append("\n");
            sb.Append("  CreationDate: ").Append(CreationDate).Append("\n");
            sb.Append("  CreatorId: ").Append(CreatorId).Append("\n");
            sb.Append("  MemberCount: ").Append(MemberCount).Append("\n");
            sb.Append("  TaxRate: ").Append(TaxRate).Append("\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetCorporationsCorporationIdOk);
        }

        /// <summary>
        /// Returns true if GetCorporationsCorporationIdOk instances are equal
        /// </summary>
        /// <param name="other">Instance of GetCorporationsCorporationIdOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCorporationsCorporationIdOk other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AllianceId == other.AllianceId ||
                    this.AllianceId != null &&
                    this.AllianceId.Equals(other.AllianceId)
                ) && 
                (
                    this.CeoId == other.CeoId ||
                    this.CeoId != null &&
                    this.CeoId.Equals(other.CeoId)
                ) && 
                (
                    this.CorporationDescription == other.CorporationDescription ||
                    this.CorporationDescription != null &&
                    this.CorporationDescription.Equals(other.CorporationDescription)
                ) && 
                (
                    this.CorporationName == other.CorporationName ||
                    this.CorporationName != null &&
                    this.CorporationName.Equals(other.CorporationName)
                ) && 
                (
                    this.CreationDate == other.CreationDate ||
                    this.CreationDate != null &&
                    this.CreationDate.Equals(other.CreationDate)
                ) && 
                (
                    this.CreatorId == other.CreatorId ||
                    this.CreatorId != null &&
                    this.CreatorId.Equals(other.CreatorId)
                ) && 
                (
                    this.MemberCount == other.MemberCount ||
                    this.MemberCount != null &&
                    this.MemberCount.Equals(other.MemberCount)
                ) && 
                (
                    this.TaxRate == other.TaxRate ||
                    this.TaxRate != null &&
                    this.TaxRate.Equals(other.TaxRate)
                ) && 
                (
                    this.Ticker == other.Ticker ||
                    this.Ticker != null &&
                    this.Ticker.Equals(other.Ticker)
                ) && 
                (
                    this.Url == other.Url ||
                    this.Url != null &&
                    this.Url.Equals(other.Url)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AllianceId != null)
                    hash = hash * 59 + this.AllianceId.GetHashCode();
                if (this.CeoId != null)
                    hash = hash * 59 + this.CeoId.GetHashCode();
                if (this.CorporationDescription != null)
                    hash = hash * 59 + this.CorporationDescription.GetHashCode();
                if (this.CorporationName != null)
                    hash = hash * 59 + this.CorporationName.GetHashCode();
                if (this.CreationDate != null)
                    hash = hash * 59 + this.CreationDate.GetHashCode();
                if (this.CreatorId != null)
                    hash = hash * 59 + this.CreatorId.GetHashCode();
                if (this.MemberCount != null)
                    hash = hash * 59 + this.MemberCount.GetHashCode();
                if (this.TaxRate != null)
                    hash = hash * 59 + this.TaxRate.GetHashCode();
                if (this.Ticker != null)
                    hash = hash * 59 + this.Ticker.GetHashCode();
                if (this.Url != null)
                    hash = hash * 59 + this.Url.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            // TaxRate (float?) maximum
            if(this.TaxRate > (float?)1)
            {
                yield return new ValidationResult("Invalid value for TaxRate, must be a value less than or equal to 1.", new [] { "TaxRate" });
            }

            // TaxRate (float?) minimum
            if(this.TaxRate < (float?)0)
            {
                yield return new ValidationResult("Invalid value for TaxRate, must be a value greater than or equal to 0.", new [] { "TaxRate" });
            }

            yield break;
        }
    }

}
