/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCharactersCharacterIdSkillsOk :  IEquatable<GetCharactersCharacterIdSkillsOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdSkillsOk" /> class.
        /// </summary>
        /// <param name="Skills">skills array.</param>
        /// <param name="TotalSp">total_sp integer.</param>
        public GetCharactersCharacterIdSkillsOk(List<GetCharactersCharacterIdSkillsSkill> Skills = default(List<GetCharactersCharacterIdSkillsSkill>), long? TotalSp = default(long?))
        {
            this.Skills = Skills;
            this.TotalSp = TotalSp;
        }
        
        /// <summary>
        /// skills array
        /// </summary>
        /// <value>skills array</value>
        [DataMember(Name="skills", EmitDefaultValue=false)]
        public List<GetCharactersCharacterIdSkillsSkill> Skills { get; set; }
        /// <summary>
        /// total_sp integer
        /// </summary>
        /// <value>total_sp integer</value>
        [DataMember(Name="total_sp", EmitDefaultValue=false)]
        public long? TotalSp { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCharactersCharacterIdSkillsOk {\n");
            sb.Append("  Skills: ").Append(Skills).Append("\n");
            sb.Append("  TotalSp: ").Append(TotalSp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetCharactersCharacterIdSkillsOk);
        }

        /// <summary>
        /// Returns true if GetCharactersCharacterIdSkillsOk instances are equal
        /// </summary>
        /// <param name="other">Instance of GetCharactersCharacterIdSkillsOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCharactersCharacterIdSkillsOk other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Skills == other.Skills ||
                    this.Skills != null &&
                    this.Skills.SequenceEqual(other.Skills)
                ) && 
                (
                    this.TotalSp == other.TotalSp ||
                    this.TotalSp != null &&
                    this.TotalSp.Equals(other.TotalSp)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Skills != null)
                    hash = hash * 59 + this.Skills.GetHashCode();
                if (this.TotalSp != null)
                    hash = hash * 59 + this.TotalSp.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
