/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetCharactersCharacterIdPlanetsPlanetIdOk :  IEquatable<GetCharactersCharacterIdPlanetsPlanetIdOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdPlanetsPlanetIdOk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetCharactersCharacterIdPlanetsPlanetIdOk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCharactersCharacterIdPlanetsPlanetIdOk" /> class.
        /// </summary>
        /// <param name="Links">links array (required).</param>
        /// <param name="Pins">pins array (required).</param>
        /// <param name="Routes">routes array (required).</param>
        public GetCharactersCharacterIdPlanetsPlanetIdOk(List<GetCharactersCharacterIdPlanetsPlanetIdLink> Links = default(List<GetCharactersCharacterIdPlanetsPlanetIdLink>), List<GetCharactersCharacterIdPlanetsPlanetIdPin> Pins = default(List<GetCharactersCharacterIdPlanetsPlanetIdPin>), List<GetCharactersCharacterIdPlanetsPlanetIdRoute> Routes = default(List<GetCharactersCharacterIdPlanetsPlanetIdRoute>))
        {
            // to ensure "Links" is required (not null)
            if (Links == null)
            {
                throw new InvalidDataException("Links is a required property for GetCharactersCharacterIdPlanetsPlanetIdOk and cannot be null");
            }
            else
            {
                this.Links = Links;
            }
            // to ensure "Pins" is required (not null)
            if (Pins == null)
            {
                throw new InvalidDataException("Pins is a required property for GetCharactersCharacterIdPlanetsPlanetIdOk and cannot be null");
            }
            else
            {
                this.Pins = Pins;
            }
            // to ensure "Routes" is required (not null)
            if (Routes == null)
            {
                throw new InvalidDataException("Routes is a required property for GetCharactersCharacterIdPlanetsPlanetIdOk and cannot be null");
            }
            else
            {
                this.Routes = Routes;
            }
        }
        
        /// <summary>
        /// links array
        /// </summary>
        /// <value>links array</value>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public List<GetCharactersCharacterIdPlanetsPlanetIdLink> Links { get; set; }
        /// <summary>
        /// pins array
        /// </summary>
        /// <value>pins array</value>
        [DataMember(Name="pins", EmitDefaultValue=false)]
        public List<GetCharactersCharacterIdPlanetsPlanetIdPin> Pins { get; set; }
        /// <summary>
        /// routes array
        /// </summary>
        /// <value>routes array</value>
        [DataMember(Name="routes", EmitDefaultValue=false)]
        public List<GetCharactersCharacterIdPlanetsPlanetIdRoute> Routes { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCharactersCharacterIdPlanetsPlanetIdOk {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Pins: ").Append(Pins).Append("\n");
            sb.Append("  Routes: ").Append(Routes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetCharactersCharacterIdPlanetsPlanetIdOk);
        }

        /// <summary>
        /// Returns true if GetCharactersCharacterIdPlanetsPlanetIdOk instances are equal
        /// </summary>
        /// <param name="other">Instance of GetCharactersCharacterIdPlanetsPlanetIdOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCharactersCharacterIdPlanetsPlanetIdOk other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.SequenceEqual(other.Links)
                ) && 
                (
                    this.Pins == other.Pins ||
                    this.Pins != null &&
                    this.Pins.SequenceEqual(other.Pins)
                ) && 
                (
                    this.Routes == other.Routes ||
                    this.Routes != null &&
                    this.Routes.SequenceEqual(other.Routes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                if (this.Pins != null)
                    hash = hash * 59 + this.Pins.GetHashCode();
                if (this.Routes != null)
                    hash = hash * 59 + this.Routes.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
