/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetFleetsFleetIdOk :  IEquatable<GetFleetsFleetIdOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFleetsFleetIdOk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetFleetsFleetIdOk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFleetsFleetIdOk" /> class.
        /// </summary>
        /// <param name="IsFreeMove">Is free-move enabled (required).</param>
        /// <param name="IsRegistered">Does the fleet have an active fleet advertisement (required).</param>
        /// <param name="IsVoiceEnabled">Is EVE Voice enabled (required).</param>
        /// <param name="Motd">Fleet MOTD in CCP flavoured HTML (required).</param>
        public GetFleetsFleetIdOk(bool? IsFreeMove = default(bool?), bool? IsRegistered = default(bool?), bool? IsVoiceEnabled = default(bool?), string Motd = default(string))
        {
            // to ensure "IsFreeMove" is required (not null)
            if (IsFreeMove == null)
            {
                throw new InvalidDataException("IsFreeMove is a required property for GetFleetsFleetIdOk and cannot be null");
            }
            else
            {
                this.IsFreeMove = IsFreeMove;
            }
            // to ensure "IsRegistered" is required (not null)
            if (IsRegistered == null)
            {
                throw new InvalidDataException("IsRegistered is a required property for GetFleetsFleetIdOk and cannot be null");
            }
            else
            {
                this.IsRegistered = IsRegistered;
            }
            // to ensure "IsVoiceEnabled" is required (not null)
            if (IsVoiceEnabled == null)
            {
                throw new InvalidDataException("IsVoiceEnabled is a required property for GetFleetsFleetIdOk and cannot be null");
            }
            else
            {
                this.IsVoiceEnabled = IsVoiceEnabled;
            }
            // to ensure "Motd" is required (not null)
            if (Motd == null)
            {
                throw new InvalidDataException("Motd is a required property for GetFleetsFleetIdOk and cannot be null");
            }
            else
            {
                this.Motd = Motd;
            }
        }
        
        /// <summary>
        /// Is free-move enabled
        /// </summary>
        /// <value>Is free-move enabled</value>
        [DataMember(Name="is_free_move", EmitDefaultValue=false)]
        public bool? IsFreeMove { get; set; }
        /// <summary>
        /// Does the fleet have an active fleet advertisement
        /// </summary>
        /// <value>Does the fleet have an active fleet advertisement</value>
        [DataMember(Name="is_registered", EmitDefaultValue=false)]
        public bool? IsRegistered { get; set; }
        /// <summary>
        /// Is EVE Voice enabled
        /// </summary>
        /// <value>Is EVE Voice enabled</value>
        [DataMember(Name="is_voice_enabled", EmitDefaultValue=false)]
        public bool? IsVoiceEnabled { get; set; }
        /// <summary>
        /// Fleet MOTD in CCP flavoured HTML
        /// </summary>
        /// <value>Fleet MOTD in CCP flavoured HTML</value>
        [DataMember(Name="motd", EmitDefaultValue=false)]
        public string Motd { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetFleetsFleetIdOk {\n");
            sb.Append("  IsFreeMove: ").Append(IsFreeMove).Append("\n");
            sb.Append("  IsRegistered: ").Append(IsRegistered).Append("\n");
            sb.Append("  IsVoiceEnabled: ").Append(IsVoiceEnabled).Append("\n");
            sb.Append("  Motd: ").Append(Motd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetFleetsFleetIdOk);
        }

        /// <summary>
        /// Returns true if GetFleetsFleetIdOk instances are equal
        /// </summary>
        /// <param name="other">Instance of GetFleetsFleetIdOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetFleetsFleetIdOk other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IsFreeMove == other.IsFreeMove ||
                    this.IsFreeMove != null &&
                    this.IsFreeMove.Equals(other.IsFreeMove)
                ) && 
                (
                    this.IsRegistered == other.IsRegistered ||
                    this.IsRegistered != null &&
                    this.IsRegistered.Equals(other.IsRegistered)
                ) && 
                (
                    this.IsVoiceEnabled == other.IsVoiceEnabled ||
                    this.IsVoiceEnabled != null &&
                    this.IsVoiceEnabled.Equals(other.IsVoiceEnabled)
                ) && 
                (
                    this.Motd == other.Motd ||
                    this.Motd != null &&
                    this.Motd.Equals(other.Motd)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IsFreeMove != null)
                    hash = hash * 59 + this.IsFreeMove.GetHashCode();
                if (this.IsRegistered != null)
                    hash = hash * 59 + this.IsRegistered.GetHashCode();
                if (this.IsVoiceEnabled != null)
                    hash = hash * 59 + this.IsVoiceEnabled.GetHashCode();
                if (this.Motd != null)
                    hash = hash * 59 + this.Motd.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
