/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetKillmailsKillmailIdKillmailHashOk :  IEquatable<GetKillmailsKillmailIdKillmailHashOk>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetKillmailsKillmailIdKillmailHashOk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetKillmailsKillmailIdKillmailHashOk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetKillmailsKillmailIdKillmailHashOk" /> class.
        /// </summary>
        /// <param name="Attackers">attackers array (required).</param>
        /// <param name="KillmailId">ID of the killmail (required).</param>
        /// <param name="KillmailTime">Time that the victim was killed and the killmail generated  (required).</param>
        /// <param name="MoonId">Moon if the kill took place at one.</param>
        /// <param name="SolarSystemId">Solar system that the kill took place in  (required).</param>
        /// <param name="Victim">Victim.</param>
        /// <param name="WarId">War if the killmail is generated in relation to an official war .</param>
        public GetKillmailsKillmailIdKillmailHashOk(List<GetKillmailsKillmailIdKillmailHashAttacker> Attackers = default(List<GetKillmailsKillmailIdKillmailHashAttacker>), int? KillmailId = default(int?), DateTime? KillmailTime = default(DateTime?), int? MoonId = default(int?), int? SolarSystemId = default(int?), GetKillmailsKillmailIdKillmailHashVictim Victim = default(GetKillmailsKillmailIdKillmailHashVictim), int? WarId = default(int?))
        {
            // to ensure "Attackers" is required (not null)
            if (Attackers == null)
            {
                throw new InvalidDataException("Attackers is a required property for GetKillmailsKillmailIdKillmailHashOk and cannot be null");
            }
            else
            {
                this.Attackers = Attackers;
            }
            // to ensure "KillmailId" is required (not null)
            if (KillmailId == null)
            {
                throw new InvalidDataException("KillmailId is a required property for GetKillmailsKillmailIdKillmailHashOk and cannot be null");
            }
            else
            {
                this.KillmailId = KillmailId;
            }
            // to ensure "KillmailTime" is required (not null)
            if (KillmailTime == null)
            {
                throw new InvalidDataException("KillmailTime is a required property for GetKillmailsKillmailIdKillmailHashOk and cannot be null");
            }
            else
            {
                this.KillmailTime = KillmailTime;
            }
            // to ensure "SolarSystemId" is required (not null)
            if (SolarSystemId == null)
            {
                throw new InvalidDataException("SolarSystemId is a required property for GetKillmailsKillmailIdKillmailHashOk and cannot be null");
            }
            else
            {
                this.SolarSystemId = SolarSystemId;
            }
            this.MoonId = MoonId;
            this.Victim = Victim;
            this.WarId = WarId;
        }
        
        /// <summary>
        /// attackers array
        /// </summary>
        /// <value>attackers array</value>
        [DataMember(Name="attackers", EmitDefaultValue=false)]
        public List<GetKillmailsKillmailIdKillmailHashAttacker> Attackers { get; set; }
        /// <summary>
        /// ID of the killmail
        /// </summary>
        /// <value>ID of the killmail</value>
        [DataMember(Name="killmail_id", EmitDefaultValue=false)]
        public int? KillmailId { get; set; }
        /// <summary>
        /// Time that the victim was killed and the killmail generated 
        /// </summary>
        /// <value>Time that the victim was killed and the killmail generated </value>
        [DataMember(Name="killmail_time", EmitDefaultValue=false)]
        public DateTime? KillmailTime { get; set; }
        /// <summary>
        /// Moon if the kill took place at one
        /// </summary>
        /// <value>Moon if the kill took place at one</value>
        [DataMember(Name="moon_id", EmitDefaultValue=false)]
        public int? MoonId { get; set; }
        /// <summary>
        /// Solar system that the kill took place in 
        /// </summary>
        /// <value>Solar system that the kill took place in </value>
        [DataMember(Name="solar_system_id", EmitDefaultValue=false)]
        public int? SolarSystemId { get; set; }
        /// <summary>
        /// Gets or Sets Victim
        /// </summary>
        [DataMember(Name="victim", EmitDefaultValue=false)]
        public GetKillmailsKillmailIdKillmailHashVictim Victim { get; set; }
        /// <summary>
        /// War if the killmail is generated in relation to an official war 
        /// </summary>
        /// <value>War if the killmail is generated in relation to an official war </value>
        [DataMember(Name="war_id", EmitDefaultValue=false)]
        public int? WarId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetKillmailsKillmailIdKillmailHashOk {\n");
            sb.Append("  Attackers: ").Append(Attackers).Append("\n");
            sb.Append("  KillmailId: ").Append(KillmailId).Append("\n");
            sb.Append("  KillmailTime: ").Append(KillmailTime).Append("\n");
            sb.Append("  MoonId: ").Append(MoonId).Append("\n");
            sb.Append("  SolarSystemId: ").Append(SolarSystemId).Append("\n");
            sb.Append("  Victim: ").Append(Victim).Append("\n");
            sb.Append("  WarId: ").Append(WarId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetKillmailsKillmailIdKillmailHashOk);
        }

        /// <summary>
        /// Returns true if GetKillmailsKillmailIdKillmailHashOk instances are equal
        /// </summary>
        /// <param name="other">Instance of GetKillmailsKillmailIdKillmailHashOk to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetKillmailsKillmailIdKillmailHashOk other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Attackers == other.Attackers ||
                    this.Attackers != null &&
                    this.Attackers.SequenceEqual(other.Attackers)
                ) && 
                (
                    this.KillmailId == other.KillmailId ||
                    this.KillmailId != null &&
                    this.KillmailId.Equals(other.KillmailId)
                ) && 
                (
                    this.KillmailTime == other.KillmailTime ||
                    this.KillmailTime != null &&
                    this.KillmailTime.Equals(other.KillmailTime)
                ) && 
                (
                    this.MoonId == other.MoonId ||
                    this.MoonId != null &&
                    this.MoonId.Equals(other.MoonId)
                ) && 
                (
                    this.SolarSystemId == other.SolarSystemId ||
                    this.SolarSystemId != null &&
                    this.SolarSystemId.Equals(other.SolarSystemId)
                ) && 
                (
                    this.Victim == other.Victim ||
                    this.Victim != null &&
                    this.Victim.Equals(other.Victim)
                ) && 
                (
                    this.WarId == other.WarId ||
                    this.WarId != null &&
                    this.WarId.Equals(other.WarId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Attackers != null)
                    hash = hash * 59 + this.Attackers.GetHashCode();
                if (this.KillmailId != null)
                    hash = hash * 59 + this.KillmailId.GetHashCode();
                if (this.KillmailTime != null)
                    hash = hash * 59 + this.KillmailTime.GetHashCode();
                if (this.MoonId != null)
                    hash = hash * 59 + this.MoonId.GetHashCode();
                if (this.SolarSystemId != null)
                    hash = hash * 59 + this.SolarSystemId.GetHashCode();
                if (this.Victim != null)
                    hash = hash * 59 + this.Victim.GetHashCode();
                if (this.WarId != null)
                    hash = hash * 59 + this.WarId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
