/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetMarketsPrices200Ok :  IEquatable<GetMarketsPrices200Ok>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsPrices200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketsPrices200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsPrices200Ok" /> class.
        /// </summary>
        /// <param name="AdjustedPrice">adjusted_price number.</param>
        /// <param name="AveragePrice">average_price number.</param>
        /// <param name="TypeId">type_id integer (required).</param>
        public GetMarketsPrices200Ok(float? AdjustedPrice = default(float?), float? AveragePrice = default(float?), int? TypeId = default(int?))
        {
            // to ensure "TypeId" is required (not null)
            if (TypeId == null)
            {
                throw new InvalidDataException("TypeId is a required property for GetMarketsPrices200Ok and cannot be null");
            }
            else
            {
                this.TypeId = TypeId;
            }
            this.AdjustedPrice = AdjustedPrice;
            this.AveragePrice = AveragePrice;
        }
        
        /// <summary>
        /// adjusted_price number
        /// </summary>
        /// <value>adjusted_price number</value>
        [DataMember(Name="adjusted_price", EmitDefaultValue=false)]
        public float? AdjustedPrice { get; set; }
        /// <summary>
        /// average_price number
        /// </summary>
        /// <value>average_price number</value>
        [DataMember(Name="average_price", EmitDefaultValue=false)]
        public float? AveragePrice { get; set; }
        /// <summary>
        /// type_id integer
        /// </summary>
        /// <value>type_id integer</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public int? TypeId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetMarketsPrices200Ok {\n");
            sb.Append("  AdjustedPrice: ").Append(AdjustedPrice).Append("\n");
            sb.Append("  AveragePrice: ").Append(AveragePrice).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetMarketsPrices200Ok);
        }

        /// <summary>
        /// Returns true if GetMarketsPrices200Ok instances are equal
        /// </summary>
        /// <param name="other">Instance of GetMarketsPrices200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetMarketsPrices200Ok other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AdjustedPrice == other.AdjustedPrice ||
                    this.AdjustedPrice != null &&
                    this.AdjustedPrice.Equals(other.AdjustedPrice)
                ) && 
                (
                    this.AveragePrice == other.AveragePrice ||
                    this.AveragePrice != null &&
                    this.AveragePrice.Equals(other.AveragePrice)
                ) && 
                (
                    this.TypeId == other.TypeId ||
                    this.TypeId != null &&
                    this.TypeId.Equals(other.TypeId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AdjustedPrice != null)
                    hash = hash * 59 + this.AdjustedPrice.GetHashCode();
                if (this.AveragePrice != null)
                    hash = hash * 59 + this.AveragePrice.GetHashCode();
                if (this.TypeId != null)
                    hash = hash * 59 + this.TypeId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
