/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// The aggressor corporation or alliance that declared this war, only contains either corporation_id or alliance_id
    /// </summary>
    [DataContract]
    public partial class GetWarsWarIdAggressor :  IEquatable<GetWarsWarIdAggressor>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWarsWarIdAggressor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetWarsWarIdAggressor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWarsWarIdAggressor" /> class.
        /// </summary>
        /// <param name="AllianceId">Alliance ID if and only if the aggressor is an alliance.</param>
        /// <param name="CorporationId">Corporation ID if and only if the aggressor is a corporation.</param>
        /// <param name="IskDestroyed">ISK value of ships the aggressor has destroyed (required).</param>
        /// <param name="ShipsKilled">The number of ships the aggressor has killed (required).</param>
        public GetWarsWarIdAggressor(int? AllianceId = default(int?), int? CorporationId = default(int?), float? IskDestroyed = default(float?), int? ShipsKilled = default(int?))
        {
            // to ensure "IskDestroyed" is required (not null)
            if (IskDestroyed == null)
            {
                throw new InvalidDataException("IskDestroyed is a required property for GetWarsWarIdAggressor and cannot be null");
            }
            else
            {
                this.IskDestroyed = IskDestroyed;
            }
            // to ensure "ShipsKilled" is required (not null)
            if (ShipsKilled == null)
            {
                throw new InvalidDataException("ShipsKilled is a required property for GetWarsWarIdAggressor and cannot be null");
            }
            else
            {
                this.ShipsKilled = ShipsKilled;
            }
            this.AllianceId = AllianceId;
            this.CorporationId = CorporationId;
        }
        
        /// <summary>
        /// Alliance ID if and only if the aggressor is an alliance
        /// </summary>
        /// <value>Alliance ID if and only if the aggressor is an alliance</value>
        [DataMember(Name="alliance_id", EmitDefaultValue=false)]
        public int? AllianceId { get; set; }
        /// <summary>
        /// Corporation ID if and only if the aggressor is a corporation
        /// </summary>
        /// <value>Corporation ID if and only if the aggressor is a corporation</value>
        [DataMember(Name="corporation_id", EmitDefaultValue=false)]
        public int? CorporationId { get; set; }
        /// <summary>
        /// ISK value of ships the aggressor has destroyed
        /// </summary>
        /// <value>ISK value of ships the aggressor has destroyed</value>
        [DataMember(Name="isk_destroyed", EmitDefaultValue=false)]
        public float? IskDestroyed { get; set; }
        /// <summary>
        /// The number of ships the aggressor has killed
        /// </summary>
        /// <value>The number of ships the aggressor has killed</value>
        [DataMember(Name="ships_killed", EmitDefaultValue=false)]
        public int? ShipsKilled { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetWarsWarIdAggressor {\n");
            sb.Append("  AllianceId: ").Append(AllianceId).Append("\n");
            sb.Append("  CorporationId: ").Append(CorporationId).Append("\n");
            sb.Append("  IskDestroyed: ").Append(IskDestroyed).Append("\n");
            sb.Append("  ShipsKilled: ").Append(ShipsKilled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetWarsWarIdAggressor);
        }

        /// <summary>
        /// Returns true if GetWarsWarIdAggressor instances are equal
        /// </summary>
        /// <param name="other">Instance of GetWarsWarIdAggressor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetWarsWarIdAggressor other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AllianceId == other.AllianceId ||
                    this.AllianceId != null &&
                    this.AllianceId.Equals(other.AllianceId)
                ) && 
                (
                    this.CorporationId == other.CorporationId ||
                    this.CorporationId != null &&
                    this.CorporationId.Equals(other.CorporationId)
                ) && 
                (
                    this.IskDestroyed == other.IskDestroyed ||
                    this.IskDestroyed != null &&
                    this.IskDestroyed.Equals(other.IskDestroyed)
                ) && 
                (
                    this.ShipsKilled == other.ShipsKilled ||
                    this.ShipsKilled != null &&
                    this.ShipsKilled.Equals(other.ShipsKilled)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AllianceId != null)
                    hash = hash * 59 + this.AllianceId.GetHashCode();
                if (this.CorporationId != null)
                    hash = hash * 59 + this.CorporationId.GetHashCode();
                if (this.IskDestroyed != null)
                    hash = hash * 59 + this.IskDestroyed.GetHashCode();
                if (this.ShipsKilled != null)
                    hash = hash * 59 + this.ShipsKilled.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
