/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// 201 created object
    /// </summary>
    [DataContract]
    public partial class PostFleetsFleetIdWingsWingIdSquadsCreated :  IEquatable<PostFleetsFleetIdWingsWingIdSquadsCreated>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostFleetsFleetIdWingsWingIdSquadsCreated" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostFleetsFleetIdWingsWingIdSquadsCreated() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostFleetsFleetIdWingsWingIdSquadsCreated" /> class.
        /// </summary>
        /// <param name="SquadId">The squad_id of the newly created squad (required).</param>
        public PostFleetsFleetIdWingsWingIdSquadsCreated(long? SquadId = default(long?))
        {
            // to ensure "SquadId" is required (not null)
            if (SquadId == null)
            {
                throw new InvalidDataException("SquadId is a required property for PostFleetsFleetIdWingsWingIdSquadsCreated and cannot be null");
            }
            else
            {
                this.SquadId = SquadId;
            }
        }
        
        /// <summary>
        /// The squad_id of the newly created squad
        /// </summary>
        /// <value>The squad_id of the newly created squad</value>
        [DataMember(Name="squad_id", EmitDefaultValue=false)]
        public long? SquadId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostFleetsFleetIdWingsWingIdSquadsCreated {\n");
            sb.Append("  SquadId: ").Append(SquadId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PostFleetsFleetIdWingsWingIdSquadsCreated);
        }

        /// <summary>
        /// Returns true if PostFleetsFleetIdWingsWingIdSquadsCreated instances are equal
        /// </summary>
        /// <param name="other">Instance of PostFleetsFleetIdWingsWingIdSquadsCreated to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostFleetsFleetIdWingsWingIdSquadsCreated other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SquadId == other.SquadId ||
                    this.SquadId != null &&
                    this.SquadId.Equals(other.SquadId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SquadId != null)
                    hash = hash * 59 + this.SquadId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
