/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// Bad request
    /// </summary>
    [DataContract]
    public partial class PutCharactersCharacterIdMailMailIdBadRequest :  IEquatable<PutCharactersCharacterIdMailMailIdBadRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutCharactersCharacterIdMailMailIdBadRequest" /> class.
        /// </summary>
        /// <param name="Error">Bad request message.</param>
        public PutCharactersCharacterIdMailMailIdBadRequest(string Error = default(string))
        {
            this.Error = Error;
        }
        
        /// <summary>
        /// Bad request message
        /// </summary>
        /// <value>Bad request message</value>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public string Error { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PutCharactersCharacterIdMailMailIdBadRequest {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PutCharactersCharacterIdMailMailIdBadRequest);
        }

        /// <summary>
        /// Returns true if PutCharactersCharacterIdMailMailIdBadRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of PutCharactersCharacterIdMailMailIdBadRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PutCharactersCharacterIdMailMailIdBadRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Error == other.Error ||
                    this.Error != null &&
                    this.Error.Equals(other.Error)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Error != null)
                    hash = hash * 59 + this.Error.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
