/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ESI.Model
{
    /// <summary>
    /// naming object
    /// </summary>
    [DataContract]
    public partial class PutFleetsFleetIdSquadsSquadIdNaming :  IEquatable<PutFleetsFleetIdSquadsSquadIdNaming>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutFleetsFleetIdSquadsSquadIdNaming" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutFleetsFleetIdSquadsSquadIdNaming() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutFleetsFleetIdSquadsSquadIdNaming" /> class.
        /// </summary>
        /// <param name="Name">name string (required).</param>
        public PutFleetsFleetIdSquadsSquadIdNaming(string Name = default(string))
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for PutFleetsFleetIdSquadsSquadIdNaming and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
        }
        
        /// <summary>
        /// name string
        /// </summary>
        /// <value>name string</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PutFleetsFleetIdSquadsSquadIdNaming {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PutFleetsFleetIdSquadsSquadIdNaming);
        }

        /// <summary>
        /// Returns true if PutFleetsFleetIdSquadsSquadIdNaming instances are equal
        /// </summary>
        /// <param name="other">Instance of PutFleetsFleetIdSquadsSquadIdNaming to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PutFleetsFleetIdSquadsSquadIdNaming other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            // Name (string) maxLength
            if(this.Name != null && this.Name.Length > 10)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 10.", new [] { "Name" });
            }

            yield break;
        }
    }

}
